### ISSUE TITLE
how to checkPendingIntents in QML

### ISSUE THREAD

**Issue by xnhw01** [timsee/QtMobileShareUtils#1]
I note that in your instructions, you say:
> You'll also need to listen to event changes in android only. This is the only surefire way to catch incoming intents.

howerver, I am developing a QtQuick app for Android. So, I would like to kown how to checkPendingIntents in qml.

Thanks.

**Comment by timsee** [comment]
Hmm, I'm not too familiar with how to handle that case in QML but this project is based off of [ekkesShare](https://github.com/ekke/ekkesSHAREexample/) which does use QML for most of its assets. I would check there! From a quick perusal it looks like it looks like it handles most of the `ShareUtils` signals/slots from QML but the application state change is still handled in the `.cpp` code: 

https://github.com/ekke/ekkesSHAREexample/blob/master/cpp/applicationui.cpp#L352-L370
